### ISSUE TITLE
Suffix not added if Object name over 30 characters

### ISSUE THREAD

**Issue by Darren-OO** [waldo1001/crs-al-language-extension#164] opened 2020-04-15 23:23 UTC
I'm finding that when adding a suffix to an object, the object is not renamed if the new name would be over 30 characters.

This gets renamed with a 4 character suffix (26 + 4 chars)
```
codeunit 50101 "Test Codeunit abcdefghijklz"
{
}
```

This does not (27 + 4 chars)
```
codeunit 50101 "Test Codeunit abcdefghijklz"
{
}
```

These are the settings that I'm using
```
"settings": {
	"CRS.ObjectNameSuffix": " ABC",
	"CRS.RemoveSuffixFromFilename": false,
	"CRS.FileNamePattern": "<ObjectNameShort>.<ObjectTypeShortPascalCase>.al",
	"CRS.FileNamePatternExtensions": "<ObjectNameShort>.<ObjectTypeShortPascalCase>.al",		
    	"CRS.FileNamePatternPageCustomizations": "<ObjectNameShort>.<ObjectTypeShortPascalCase>.al",
	"CRS.OnSaveAlFileAction": "Rename",
	"CRS.ObjectNamePrefix": "",
	"CRS.RenameWithGit": false
}
```

I get the same kind of results with RemoveSuffixFromFilename true or false. Is this functionality intentional?
I'd rather that everything got renamed with a suffix and then I could go through the errors and fix object names as required.
I'm using CRS 1.2.1.

**Comment by waldo1001** [comment] 2020-04-27 13:12
It is by design.

If I would rename it, in case of Table-Ext and Page-Ext, which can be set up to auto naming as well - would end up in an endless loop (not a possibility to give a decent name.

The only drawback now is indeed to auto-rename for all files. 

But - a workaround could be:
Set up the codecops that check for affixes (AppSourceCop), set up the AppSourceCop.json, and you'll see all files that are not affixed correctly.

Hope this helps.  I'll close this issue as "by design".

**Closed by waldo1001** 2020-04-27 13:12 UTC
Labels: By Design
