### ISSUE TITLE
Default Filename does not match best practice after rename

### ISSUE THREAD

**Issue by ChrisBlankDe** [waldo1001/crs-al-language-extension#119] opened 2019-06-03 21:11 UTC
If FileNamePatternExtensions and FileNamePattern is not configured in settings, page extensions are named like `Pag-Ext50100.CustomerListExt.al`. This does not match the best practice from [Best Practices for AL - File naming](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode#file-naming).

As I read the docs the file should be named `PagExt21-Ext50100.CustomerListExt.al`.

I think the default setting should match the best practice from Microsoft.

What do you think?

**Comment by waldo1001** [comment] 2019-06-04 14:34
Well - Microsoft changed its own rules - I had implemented the default, but now they changed.. .

The problem is that when I change the default myself, a lot of people that use the default setting, might have unexpected file name changes.  And if they don't have the "RenameWithGit" switched on (which preserves the history of the file), it might be something they will blame me for .. :(.

an option would be that in the same update, I make the "RenameWithGit" default, but I'm not that confident of that feature just yet - recently went through a lot of fuss to make it work - which it does now, but not sure if I covered all scenarios.. :-/

So, what do you think .. ?

**Comment by waldo1001** [comment] 2019-06-04 18:40
If you don't mind - I'm gong to leave it as is .. and close this comment.  I AM going to implement the other one (controladdins) though .. .

thanks again for the feedback!

**Closed by waldo1001** 2019-06-04 18:40 UTC
